; ================================================================
; PlatformIO Project Configuration
; SmartAgro Siramku - ESP32 Firmware
; ================================================================

[platformio]
; Build dir tanpa spasi (fix bug PlatformIO dengan path berspasi)
build_dir = C:\.pio_build\SmartAgroSiramku

[env:esp32dev]
platform      = espressif32 @ 6.6.0
board         = esp32dev
framework     = arduino
upload_port   = COM3
upload_speed  = 921600

; Library yang dibutuhkan
lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

; Baud rate untuk Serial Monitor (Debugging)
monitor_speed = 115200
