[platformio]
build_dir = C:\.pio_build\SmartAgroSiramku

[env:esp32dev]
platform = espressif32 @ 6.6.0
board = esp32dev
framework = arduino
upload_port = COM5
upload_speed = 460800
upload_resetmethod = default_reset

lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

monitor_speed = 115200